export const GET_CART_ITEMS_INCREMENT = "GET_CART_ITEMS_INCREMENT"

export const GET_ALL_DATA_PRODUCTS = "GET_ALL_DATA_PRODUCTS"

export const GET_ALL_DATA_PHONES = "GET_ALL_DATA_PHONES"

export const GET_ALL_DATA_TABLETS = "GET_ALL_DATA_TABLETS"

export const GET_CERTAIN_DATA_ITEM = "GET_CERTAIN_DATA_ITEM"

export const GET_ALL_PRODUCTS_CART = "GET_ALL_PRODUCTS_CART"

export const GET_ALL_PRODUCTS_CART_LAPTOPS = "GET_ALL_PRODUCTS_CART_LAPTOPS"

export const GET_ALL_PRODUCTS_CART_TABLETS = "GET_ALL_PRODUCTS_CART_TABLETS"

export const GET_ALL_PRODUCTS_DATA_CARTS = "GET_ALL_PRODUCTS_DATA_CARTS"

export const DELETE_ITEM_FROM_PRODUCTS_CART = "DELETE_ITEM_FROM_PRODUCTS_CART"

export const GET_DATA_USER = "GET_DATA_USER" ;

export const ADD_NEW_USER ="ADD_NEW_USER"

